#!/usr/bin/env python3
"""Generate Rust alphabet pack modules from data/alphabets/*.txt.

Source of truth: one alphabet cell per line (no trailing space/comma/period).
The web UI loads cells from WASM (`alphabet_symbols_json`) — no JS mirror.

Regenerate after editing those files:

  mise run gen-alphabets

Do not hand-edit the generated outputs.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "alphabets"
RUST_OUT = ROOT / "src" / "config" / "generated" / "packs.rs"

# (txt stem, rust const name)
PACKS = (
    ("chinese", "CHINESE"),
    ("chinese_trad", "CHINESE_TRAD"),
    ("thai", "THAI"),
    ("khmer", "KHMER"),
    ("amharic", "AMHARIC"),
    ("japanese", "JAPANESE"),
    ("korean", "KOREAN"),
    ("hindi", "HINDI"),
    ("bengali", "BENGALI"),
    ("tamil", "TAMIL"),
    ("telugu", "TELUGU"),
    ("kannada", "KANNADA"),
    ("malayalam", "MALAYALAM"),
    ("gujarati", "GUJARATI"),
    ("punjabi", "PUNJABI"),
    ("odia", "ODIA"),
    ("vietnamese", "VIETNAMESE"),
)

TRAIL = (" ", ",", ".")


def load_cells(stem: str) -> list[str]:
    path = DATA / f"{stem}.txt"
    cells: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        cells.append(line)
    if not cells:
        raise SystemExit(f"{path}: empty pack")
    return cells


def rust_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_rust(packs: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        "//! Auto-generated by `scripts/gen-alphabet-packs.py` — do not edit.",
        "//! Source: `data/alphabets/*.txt` (cells only; trailing punct added here).",
        "",
    ]
    for _stem, const, cells in packs:
        full = [*cells, *TRAIL]
        lines.append(f"/// {len(full)} alphabet cells (incl. space/comma/period).")
        lines.append(f"pub const {const}: &[&str] = &[")
        row: list[str] = []
        for cell in full:
            row.append(f'"{rust_escape(cell)}"')
            if len(row) >= 12:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    loaded: list[tuple[str, str, list[str]]] = []
    for stem, const in PACKS:
        cells = load_cells(stem)
        loaded.append((stem, const, cells))
        print(f"{stem:14} {len(cells):4} cells (+3 punct → {len(cells) + 3})")

    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(emit_rust(loaded), encoding="utf-8")
    # Keep style stable with `cargo fmt` / CI.
    import subprocess

    subprocess.run(
        ["rustfmt", "--edition", "2024", str(RUST_OUT)],
        check=False,
    )
    print(f"wrote {RUST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
